const c=window.IBGV_CONFIG||{}, ok=c.SUPABASE_URL&&!c.SUPABASE_URL.startsWith('PEGA_');let db;
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const normalizeUrl=(v='')=>{let x=String(v).trim();if(!x)return '';if(!/^https?:\/\//i.test(x))x='https://'+x;try{const u=new URL(x);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
if(!ok){setup.style.display='block';loginBtn.disabled=true}else{db=supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY);init()}
async function init(){const {data:{session}}=await db.auth.getSession();render(session);db.auth.onAuthStateChange((_e,s)=>render(s))}
function render(s){login.hidden=!!s;dashboard.hidden=!s;if(s){loadSettings();loadSermons();loadLeaders();loadAlbums()}}
loginBtn.onclick=async()=>{let {error}=await db.auth.signInWithPassword({email:email.value,password:password.value});msg.textContent=error?error.message:''};logout.onclick=()=>db.auth.signOut();
const settingKeys=['about','sunday','wednesday','address','whatsapp','lunch_text','maps_url','facebook_url','youtube_url','instagram_url','other_social_url'];
async function loadSettings(){let {data}=await db.from('settings').select('*').eq('id',1).single();if(data){settingKeys.forEach(k=>{const el=document.getElementById(k);if(el)el.value=data[k]||''});lunch_enabled.checked=data.lunch_enabled!==false}}
saveSettings.onclick=async()=>{let payload={id:1,lunch_enabled:lunch_enabled.checked};settingKeys.forEach(k=>payload[k]=document.getElementById(k).value);['maps_url','facebook_url','youtube_url','instagram_url','other_social_url'].forEach(k=>{if(payload[k])payload[k]=normalizeUrl(payload[k])});let {error}=await db.from('settings').upsert(payload);alert(error?error.message:'Cambios guardados')};
addSermon.onclick=async()=>{if(!title.value.trim())return alert('Escribe el título.');const yt=normalizeUrl(youtube.value);if(youtube.value.trim()&&!yt)return alert('El enlace de YouTube no es válido.');let payload={title:title.value.trim(),passage:passage.value.trim(),book:book.value.trim(),series:series.value.trim(),preacher:preacher.value.trim(),preached_on:preached_on.value||null,youtube_url:yt};let {error}=await db.from('sermons').insert(payload);if(error)return alert(error.message);title.value=passage.value=book.value=series.value=preacher.value=preached_on.value=youtube.value='';loadSermons()};
async function loadSermons(){let {data}=await db.from('sermons').select('*').order('created_at',{ascending:false});document.getElementById('admin-sermons').innerHTML=(data||[]).map(x=>`<div class="row admin-item"><span class="grow"><b>${esc(x.title)}</b> ${esc(x.passage||'')} ${x.book?'· '+esc(x.book):''} ${x.series?'· Serie: '+esc(x.series):''}</span><button class="btn danger" onclick="delSermon('${x.id}')">Eliminar</button></div>`).join('')}
window.delSermon=async id=>{if(confirm('¿Eliminar este sermón?')){let {error}=await db.from('sermons').delete().eq('id',id);if(error)alert(error.message);else loadSermons()}};
async function uploadImage(file,prefix){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${prefix}/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('site-images').upload(path,file,{upsert:false});if(error)throw error;return db.storage.from('site-images').getPublicUrl(path).data.publicUrl}
addLeader.onclick=async()=>{try{if(!leader_name.value.trim())return alert('Escribe el nombre.');const photo_url=await uploadImage(leader_photo.files[0],'leadership');const {error}=await db.from('leadership').insert({name:leader_name.value,role:leader_role.value,bio:leader_bio.value,photo_url,visible:leader_visible.checked});if(error)throw error;leader_name.value=leader_role.value=leader_bio.value='';leader_photo.value='';leader_visible.checked=true;loadLeaders()}catch(e){alert(e.message)}};
async function loadLeaders(){const {data}=await db.from('leadership').select('*').order('sort_order').order('created_at');document.getElementById('admin-leaders').innerHTML=(data||[]).map(x=>`<div class="row admin-item"><span class="grow"><b>${esc(x.name)}</b> · ${esc(x.role||'')} ${x.visible?'':'(oculto)'}</span><button class="btn" onclick="toggleLeader('${x.id}',${!x.visible})">${x.visible?'Ocultar':'Mostrar'}</button><button class="btn danger" onclick="delLeader('${x.id}')">Eliminar</button></div>`).join('')}
window.toggleLeader=async(id,v)=>{const {error}=await db.from('leadership').update({visible:v}).eq('id',id);if(error)alert(error.message);else loadLeaders()};window.delLeader=async id=>{if(confirm('¿Eliminar esta persona del liderazgo?')){const {error}=await db.from('leadership').delete().eq('id',id);if(error)alert(error.message);else loadLeaders()}};
addAlbum.onclick=async()=>{try{if(!album_title.value.trim())return alert('Escribe el título del álbum.');const url=normalizeUrl(album_url.value);if(!url)return alert('Escribe un enlace válido para el álbum.');const cover_url=await uploadImage(album_cover.files[0],'album-covers');const {error}=await db.from('albums').insert({title:album_title.value.trim(),description:album_description.value.trim(),album_url:url,cover_url,event_date:album_date.value||null,visible:album_visible.checked});if(error)throw error;album_title.value=album_description.value=album_url.value=album_date.value='';album_cover.value='';album_visible.checked=true;loadAlbums()}catch(e){alert(e.message)}};
async function loadAlbums(){const {data,error}=await db.from('albums').select('*').order('sort_order').order('created_at',{ascending:false});if(error){document.getElementById('admin-albums').innerHTML='<p class="muted">Ejecuta primero upgrade-v5.sql en Supabase.</p>';return}document.getElementById('admin-albums').innerHTML=(data||[]).map(x=>`<div>${x.cover_url?`<img src="${x.cover_url}" alt="">`:''}<small><b>${esc(x.title)}</b> ${x.visible?'':'(oculto)'}</small><br><button class="btn" onclick="toggleAlbum('${x.id}',${!x.visible})">${x.visible?'Ocultar':'Mostrar'}</button> <button class="btn danger" onclick="delAlbum('${x.id}')">Eliminar</button></div>`).join('')}
window.toggleAlbum=async(id,v)=>{const {error}=await db.from('albums').update({visible:v}).eq('id',id);if(error)alert(error.message);else loadAlbums()};
window.delAlbum=async id=>{if(confirm('¿Eliminar este álbum de la web? El álbum externo no se borrará.')){const {error}=await db.from('albums').delete().eq('id',id);if(error)alert(error.message);else loadAlbums()}};
