/* Complemento independiente: gestión de reuniones IBGV */
(() => {
 const root = document.getElementById('dashboard');
 if (!root) return;
 const panel = document.createElement('section'); panel.className='panel';
 panel.innerHTML=`<h2>Programa de reuniones</h2><p class="muted">Agregá, editá u ocultá actividades. Los cambios se reflejan en la página principal.</p>
 <input type="hidden" id="meeting_id"><div class="grid"><div><label>Día</label><select id="meeting_day"><option value="domingo">Domingo — Día del Señor</option><option value="miercoles">Miércoles — Noche de Oración</option></select></div><div><label>Actividad</label><input id="meeting_title" placeholder="Culto de adoración"></div><div><label>Hora de inicio</label><input id="meeting_start" type="time"></div><div><label>Hora de finalización</label><input id="meeting_end" type="time"></div><div><label>Orden (número)</label><input id="meeting_order" type="number" min="0" value="0"></div></div>
 <label class="check"><input id="meeting_visible" type="checkbox" checked> Mostrar en el sitio</label><div class="row"><button class="btn" id="meeting_save" type="button">Agregar actividad</button><button class="btn secondary" id="meeting_cancel" type="button">Cancelar edición</button></div><p id="meeting_msg" role="status"></p><div id="meeting_list"></div>`;
 const first = root.querySelector('section.panel'); first?.after(panel);
 const el=id=>document.getElementById(id); let db=null;
 function client(){if(db)return db; const c=window.IBGV_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_ANON_KEY)return null;return db=supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY)}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function reset(){['meeting_id','meeting_title','meeting_start','meeting_end'].forEach(x=>el(x).value='');el('meeting_day').value='domingo';el('meeting_order').value='0';el('meeting_visible').checked=true;el('meeting_save').textContent='Agregar actividad'}
 let records=[];
 async function load(){const c=client();if(!c)return;const {data,error}=await c.from('meeting_schedule').select('*').order('day').order('sort_order').order('start_time');if(error){el('meeting_msg').textContent='Error: '+error.message;return}records=data||[];el('meeting_list').innerHTML=records.map(x=>`<div class="row admin-item"><span class="grow"><b>${esc(x.title)}</b> · ${x.day==='domingo'?'Domingo':'Miércoles'} · ${esc(x.start_time?.slice(0,5))}–${esc(x.end_time?.slice(0,5))}${x.visible?'':' (oculto)'}</span><button type="button" class="btn secondary" data-action="edit" data-id="${x.id}">Editar</button><button type="button" class="btn" data-action="toggle" data-id="${x.id}">${x.visible?'Ocultar':'Mostrar'}</button><button type="button" class="btn danger" data-action="delete" data-id="${x.id}">Eliminar</button></div>`).join('')||'<p>No hay actividades todavía.</p>'}
 el('meeting_save').onclick=async()=>{const c=client();if(!c)return;const title=el('meeting_title').value.trim(),start=el('meeting_start').value,end=el('meeting_end').value;if(!title||!start||!end){el('meeting_msg').textContent='Completá la actividad y ambas horas.';return}if(start>=end){el('meeting_msg').textContent='La hora de finalización debe ser posterior al inicio.';return}const payload={day:el('meeting_day').value,title,start_time:start,end_time:end,sort_order:Number(el('meeting_order').value)||0,visible:el('meeting_visible').checked};const id=el('meeting_id').value;const {error}=id?await c.from('meeting_schedule').update(payload).eq('id',id):await c.from('meeting_schedule').insert(payload);el('meeting_msg').textContent=error?'Error: '+error.message:'Actividad guardada correctamente.';if(!error){reset();await load()}};
 el('meeting_cancel').onclick=reset;
 el('meeting_list').onclick=async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const x=records.find(r=>String(r.id)===b.dataset.id);if(!x)return;const action=b.dataset.action;if(action==='edit'){el('meeting_id').value=x.id;el('meeting_day').value=x.day;el('meeting_title').value=x.title;el('meeting_start').value=x.start_time.slice(0,5);el('meeting_end').value=x.end_time.slice(0,5);el('meeting_order').value=x.sort_order;el('meeting_visible').checked=x.visible;el('meeting_save').textContent='Guardar cambios';panel.scrollIntoView({behavior:'smooth'});return}if(action==='delete'&&!confirm('¿Eliminar esta actividad?'))return;const c=client();const {error}=action==='delete'?await c.from('meeting_schedule').delete().eq('id',x.id):await c.from('meeting_schedule').update({visible:!x.visible}).eq('id',x.id);el('meeting_msg').textContent=error?'Error: '+error.message:'';if(!error)await load()};
 // La sesión del administrador existente controla el panel.
 const observer=new MutationObserver(()=>{if(!root.hidden)load()});observer.observe(root,{attributes:true,attributeFilter:['hidden']});
 if(!root.hidden)load();
})();
